### ISSUE TITLE
The basics: lctest.pharr not found

### ISSUE THREAD

**Issue by mjpsr11** [ltonetwork/documentation#6]
This tutorial needs updating. The file https://github.com/legalthings/livecontracts-tester/raw/master/lctest.pharr in the last instruction cannot be found.

**Comment by Ruben1701** [comment]
If you use change it to:  https://github.com/legalthings/livecontracts-tester/raw/master/lctest.phar it will work. But does need to be updated yes.

**Comment by justmvg** [comment]
Filed pull request #8 for this.
